ARN_CERTIFICATE: "tbd"
ARN_DB_UPLOAD_STREAM: "tbd"

# AUTH0_CLIENT_ID: ${ssm:auth0-client-id~true}
# AUTH0_CLIENT_SECRET: ${ssm:auth0-client-secret~true}
# AUTH0_DOMAIN: ${ssm:auth0-domain}
# AUTH0_AUDIENCE: ${ssm:auth0-audience}

DB_TABLE_MAIN: dev-main
DB_ENDPOINT: "https://dynamodb.us-east-1.amazonaws.com"
GSI_2_INDEX_NAME: "gsi-pk-2-index"
GSI_INDEX_NAME: "gsi-pk-gsi-sk-index"

DOMAIN_NAME_API: api.dev.tbd.io
DOMAIN_NAME_WEB_APP: dev.tbd.io

LOGGER_LEVEL: ${env:LOGGER_LEVEL,"verbose"}

NODE_ENV: production
STAGE: dev
SERVERLESS_STAGE: dev
SERVERLESS_REGION: us-east-1
