ARN_CERTIFICATE: "tbd"
ARN_DB_UPLOAD_STREAM: "tbd"

# AUTH0_CLIENT_ID: ${ssm:auth0-client-id~true} 
# AUTH0_CLIENT_SECRET: ${ssm:auth0-client-secret~true}
# AUTH0_DOMAIN: ${ssm:auth0-domain}
# AUTH0_AUDIENCE: ${ssm:auth0-audience}

DB_TABLE_MAIN: test-main

DOMAIN_NAME_API: api.test.tbd.io
DOMAIN_NAME_WEB_APP: test.tbd.io

LOGGER_LEVEL: ${env:LOGGER_LEVEL,"verbose"}

NODE_ENV: production
STAGE: test
SERVERLESS_STAGE: test
SERVERLESS_REGION: us-east-1
